version: '3'
services:
  app:
    image: node:11-alpine
    volumes:
      - .:/data
    working_dir: /data
    environment:
      - NODE_ENV=test
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
